{% set name = "dogpile.cache" %}
{% set version = "1.0.2" %}
{% set sha256 = "64fda39d25b46486a4876417ca03a4af06f35bfadba9f59613f9b3d748aa21ef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - six
  run:
    - python
    - decorator
    - six

test:
  imports:
    - dogpile.cache

about:
  home: https://bitbucket.org/zzzeek/dogpile.cache
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A caching front-end based on the Dogpile lock.

extra:
  recipe-maintainers:
    - brainstorm
