{% set name = "dogpile.cache" %}
{% set version = "0.8.0" %}
{% set sha256 = "70f5eae4aec908f76188a2c287e07105f60c05d879bb9a4efcc5ba44563d8de6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."

requirements:
  host:
    - python
    - pip
    - six
  run:
    - python
    - decorator
    - six

test:
  imports:
    - dogpile.cache

about:
  home: https://bitbucket.org/zzzeek/dogpile.cache
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A caching front-end based on the Dogpile lock.

extra:
  recipe-maintainers:
    - brainstorm
